### PR TITLE
Unit test - minimal changes

### PR DESCRIPTION
**Pull request by freethlua**
Try this

### CODE REVIEW

**Comment by JoshuaVSherman** [comment]
@freethlua 
I have this code running, and I really appreciate your efforts.
Please tell me how you would like to be paid, and how I can pay you.
I am going to spend a bit more time reviewing it, before I merge it though.

thanks again!

also, let me know if you are interested in more tasks, we have them on our board in the frontend repo
also, you can submit your own issues into the backlog and we can discuss them, however, you would need to be available at the 8pm Eastern Time google hangouts scrum meeting tomorrow.

**Comment by JoshuaVSherman** [comment]
@freethlua 
I would like to pay $100 for this merge, and i'm not going to merge the code until I know how to pay you for it. We can pay though guru if you want, or I can pay you directly to paypal, just let me know

**Comment by freethlua** [comment]
Please go ahead and release the amount on guru this time. I'd like to discuss the possibility of a further job via email if that's ok, please ping me at `freethlua<@>gmail.com`

**Comment by JoshuaVSherman** [comment]
@freethlua 
Thanks again for your efforts. The ideas you had in the unit-test branch are very exciting, and we might want to incorporate them in the future, so I would like to keep in touch. We have a weekly scrum meeting at   8pm eastern time on Google Hangouts, so I will go ahead and invite you to that meeting if you are interested in discussing the task board and taking on more work.

**Comment by freethlua** [comment]
No problems. Please send me an email, I'd like to discuss this further.

**Comment by JoshuaVSherman** [comment]
@freethlua 
sorry, I don't see your gmail address, please send it to me at
joshua.v.sherman@gmail.com

thanks,
Josh Sherman

**Pull request merged**
