### PR TITLE
Unit test

### PR DESCRIPTION
**Pull request by freethlua**
This is regarding the "Unit Testing" job on Guru.

This achieves 100% coverage for auth/google.js and authUtils.js

Please test it out and let me know.

### CODE REVIEW

**Comment by JoshuaVSherman** [comment]
@freethlua 
Awesome effort here, however, you missed some important package.json
node module dependancies. I was unable to start the server or run the tests. 
please update the package.json and let me know so I can try reinstalling them.
for example, it was expecting a webpack, also some beta versions of things
possibly you installed them globally, but forgot to
npm install --save-dev

**Comment by JoshuaVSherman** [comment]
@freethlua 
image

also there is probably some issue with using the alpha version of babel-plugin-rewire

**Comment by JoshuaVSherman** [comment]
@freethlua 
So it looks to me like there is definitely a missing webpack configuration also, and that it builds a dist folder now, which is okay, but since I can't run it and test it all out, I have nothing to work on today :(
let me know what you would like to do next with resolving these issues and payment method for your work (after I can confirm it all runs as expected).

**Comment by JoshuaVSherman** [comment]
@freethlua 
The other issue I have is that you are online working when i'm asleep and vice versa.
Please provide your available times for having a face-to-face Google hangout and screen share/video call

**Comment by freethlua** [comment]
Please try this now. 

The other PR offers a minimal set of changes to achieve the unit test job. **But** please consider merging this PR instead. I'll make sure it works for you. This employs a lot of good practices.

* added the missing dependencies. 

* added the required build scripts. 

* updated to work in Docker

I've tested it in docker so I think it should work now. Also updated dockerfile a little bit. 

It only uses `babel`, no `webpack`. The warnings are only peer and optional dependencies, some packages only optionally use them. They shouldn't be a problem.

**Pull request closed without merging**
